export const guideFunctionality = [
    {
        name: "Bienvenue",
        shortcutName: "Bienvenue",
        shortDescription:"text goes here",
        description: "text goes here",
        icon:"nothing"
    },
    {
      name: "Créer un nouveau dessin",
      shortcutName: "Créer",
      shortDescription:"text goes here",
      description: "text goes here",
      icon :"add_circle",
    },
    {
        name: "Continuer un dessin",
        shortcutName: "Continuer",
        shortDescription:"text goes here",
        description: "text goes here",
        icon :"arrow_forward",  
    },
    {
        name: "Galerie de dessins",
        shortcutName: "Galerie",
        shortDescription:"text goes here",
        description: "text goes here",
        icon :"camera",  
    },
    {
        name : "Crayon",
        shortcutName: "Crayon",
        shortDescription:"text goes here",
        description: "text goes here",
        icon :"../../../assets/images/pencil.png",  
    },
    {
        name: "Rectangle",
        shortcutName:"Rectangle",
        shortDescription:"text goes here",
        description: "text goes here",
        icon: "../../../assets/images/frame.png"
    },
    {
        name: "Plume",
        shortcutName:"Plume",
        shortDescription:"text goes here",
        description: "text goes here",
        icon: "../../../assets/images/calligraphie.png",
    },
    {
        name: "Outil de sélection de couleur",
        shortcutName:"Outil couleur",
        shortDescription:"text goes here",
        description: "text goes here",
        icon: "../../../assets/images/exclude.png",
    },
    {
        name: "Élipse",
        shortcutName:"Élipse",
        shortDescription:"text goes here",
        description: "text goes here",
        icon: "../../../assets/images/oval.png",
    },
    {
        name: "Ligne",
        shortcutName:"Ligne",
        shortDescription:"text goes here",
        description: "text goes here",
        icon: "../../../assets/images/graph.png",
    },
    {
        name: "Chemin",
        shortcutName:"Chemin",
        shortDescription:"text goes here",
        description: "text goes here",
        icon: "../../../assets/images/timeline.png",
    },
    {
        name: "Pinceau",
        shortcutName:"Pinceau",
        shortDescription:"text goes here",
        description: "text goes here",
        icon: "../../../assets/images/edit-tools.png",
    },
    {
        name: "Efface",
        shortcutName:"Efface",
        shortDescription:"text goes here",
        description: "text goes here",
        icon: "../../../assets/images/eraser.png",
    },
    {
        name: "Polygone",
        shortcutName:"Polygone",
        shortDescription:"text goes here",
        description: "text goes here",
        icon: "../../../assets/images/hexagon.png",
    },
    {
        name: "Pipette",
        shortcutName:"Pipette",
        shortDescription:"text goes here",
        description: "text goes here",
        icon: "../../../assets/images/lab.png",
    },
    {
        name: "Aérosol",
        shortcutName:"Aérosol",
        shortDescription:"text goes here",
        description: "text goes here",
        icon: "../../../assets/images/spray.png",
    },    
];